### ISSUE TITLE
show spaces only at the end of line

### ISSUE THREAD

**Issue by tino926** [marph91/joplin-plugin-whitespacer#1]
Thanks for the plugin.
If it is possible, I wish there is an option to show white spaces only at the end of each line.

**Comment by marph91** [comment]
Hi, I will check if it's possible. Not sure when I will have time for it, though.

**Comment by marph91** [comment]
I just found out about https://github.com/personalizedrefrigerator/joplin-plugin-extra-editor-settings?tab=readme-ov-file#available-settings. It has a setting "Highlight trailing spaces" that should fit your use case.
