### ISSUE TITLE
Does not work with beta Markdown editor

### ISSUE THREAD

**Issue by taw00** [marph91/joplin-plugin-whitespacer#4]
Joplin 2.14.22

- Options > General > "Opt-in to the editor beta" click checkbox.
- Whitespace markings disappear

I realize that the beta markdown editor is beta, but still … It's been beta a long time. I don't know what Joplin 3.0 is using, but, I suspect it is the same editor.

**Comment by marph91** [comment]
Thanks for the report. I will try to look into it when I have time.

In Joplin 3.0.8, the beta editor shows spaces, but doesn't show line endings.

**Comment by marph91** [comment]
The fix should be available in release 1.0.1 soon. If it's not fixed for you, feel free to reopen the issue.
