### ISSUE TITLE
Tabs are not shown with new markdown editor

### ISSUE THREAD

**Issue by gcharFR** [marph91/joplin-plugin-whitespacer#5]
The Latest version of Joplin desktop (3.1.20) switched by default to the new markdown editor so this is annoying.

version of WhiteSpacer used : 1.0.1 (latest to date)

**Comment by gcharFR** [comment]
exemple :
![image](https://github.com/user-attachments/assets/4d8e12e4-96b4-46a3-9af6-5debd15d21b2)

**Comment by gcharFR** [comment]
This happens at least on Linux

**Comment by marph91** [comment]
Thanks for the report. I can reproduce it and will check how to fix it. ~~Not sure when I will have time to implement the fix, though.~~ Actually, there is a straight-forward fix, that's compatible with the old editor (Codemirror 5), too.

I just found another bug with newlines that I will try to fix before releasing.

**Comment by marph91** [comment]
I just released [version 1.0.2](https://www.npmjs.com/package/joplin-plugin-whitespacer?activeTab=versions) with the fix. It should be available in Joplin later today.

**Comment by gcharFR** [comment]
My (wild) guess‌ was the fix woulb be easy but I would never have expected to that point, thanks a lot and congrats !

Regards

Grégory
 

De : "marph91" ***@***.***>
A : "marph91/joplin-plugin-whitespacer" ***@***.***>,"gcharFR" ***@***.***>,"Author" ***@***.***>
Envoyé: lundi 28 Octobre 2024 17:49
Objet : Re: [marph91/joplin-plugin-whitespacer] Tabs are not shown with new markdown editor (Issue #5)
 

 

I just released version 1.0.2 with the fix. It should be available in Joplin later today.
